### ISSUE TITLE
Installation of cvxcanon

### ISSUE THREAD

**Issue by tschm** [jacklzhu/CVXcanon#7] opened 2015-09-21 15:43 UTC
Hi, 

I have some problems with installing the package
I try to install via pip directly from your git rep (you may want to create releases here, e.g. tags)

In my requirements.txt I use
git+https://github.com/cvxgrp/CVXcanon.git#egg=cvxcanon

The error message I get refers to an egg problem:

Could not find .egg-info directory in install record for cvxcanon from git+http://github.com/cvxgrp/CVXcanon.git#egg=cvxcanon

I am running Ubuntu 64bit.
Any hints are very appreciated. This is a part of the bigger attempt to install cvxpy.

Thanks

thomas

**Comment by millerjohnp** [comment] 2015-09-21 19:28
Hi Thomas, 

Thanks for pointing out that we still need to create releases/tags on the git repo. I'll fix that asap.

What is the exact error message that you're getting?

When I try call `pip install git+http://github.com/cvxgrp/CVXcanon.git#egg=cvxcanon` on my machine running 64 bit Ubuntu, I also get the warning

`Could not find .egg-info directory in install record for cvxcanon from git+http://github.com/cvxgrp/CVXcanon.git`, 

but CVXcanon still successfully installs for me. This warning is innoccuous and shouldn't affect the performance on CVXcanon.

Also, is there a reason that your requirements.txt is installing directly from the git repo instead of using the more stable releases on pypi?

I just double checked and the release on pypi also successfully installs on 64 bit Ubuntu for me.

Since you're building CVXcanon from source, do you have swig installed? The  binaries on pypi don't require swig to compile, but building directly from source does. I'll update the readme to make this more clear.

Let me know how I can help get this installed, and I would very much appreciate any feedback on parts of the installation process that are unclear or could use more work. 

Thanks!

John

**Comment by tschm** [comment] 2015-09-21 20:50
Thanks John, that's a detailed answer. I started with pypi (and cvxpy) and drilled down from there. I try to avoid stuff like swig whenever I can.  The innoccuous warning can probably be removed by providing the required egg folder? But I don't know such details. I have swig installed and also made atlas available. The installation of cvxopt isn't trivial either. Ideally you get the cvxpy package into anaconda?

**Comment by SteveDiamond** [comment] 2015-09-28 06:51
I've seen a nasty (but innocuous) warning message too. @ajfriend describes it here: https://github.com/cvxgrp/cvxpy/issues/230

@tschm does `pip install cvxpy` not work for you? Assuming you have numpy installed, pip install should work.

**Comment by millerjohnp** [comment] 2015-09-28 07:53
I think I've removed the `Could not find .egg-info directory in install record for cvxcanon` warning by adding `PKG-INFO` to the local project tree. This just involves running `python setup.py egg_info` before uploading the distribution to pypi, so the issue should hopefully go away when the next CVXcanon version is uploaded. 

@SteveDiamond do you have any idea what is causing the message you referenced? I'm not sure why the install is trying to also build a wheel and, even then, what is the issue that is causing it to fail. I can, however, reproduce the error.

**Comment by SteveDiamond** [comment] 2015-09-29 03:02
The error must be due to how virtual environments change the pythonpath. 

This might be relevant for why it tries to build a wheel: https://pip.pypa.io/en/latest/reference/pip_install/#wheel-cache
It suggests that setuptools will try to make a more specific wheel.

You could release a new version of CVXcanon if you've fixed the `.egg-info` warning. I also committed a fix recently for a bug I encountered.

**Comment by SteveDiamond** [comment] 2015-09-30 00:01
I noticed that you have eggs instead of wheels on PyPi (https://pypi.python.org/pypi/CVXcanon/0.0.18). You should change it back to wheels. pip might be installing from the egg and then still building a wheel because pip always builds wheels and caches them.

**Comment by millerjohnp** [comment] 2015-10-01 07:06
I just released a new version of CVXcanon. This version does not have any dependency on SWIG, has macosx wheels to speed up installation, and, as far as I can tell, does not produce either the ```.egg-info''' warning or the warning related to the pythonpath on either mac or linux.

**Comment by SteveDiamond** [comment] 2015-10-01 16:42
Great! The installation worked perfectly for me.

**Closed as completed by SteveDiamond** 2015-10-01 16:42 UTC
